services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  postgres:
    container_name: postgres
    image: postgres
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=gusto
      - POSTGRES_PASSWORD=codetest
      - POSTGRES_DB=lucky_draw
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    # depends_on:
    #   - postgres
    # restart: on-failure
volumes:
  postgres:
